default:
  ALLOWED_HOSTS: [ ]
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .tests_artifacts
  DIRS_RESOURCES:
    - config
    - scripts
    - src/project/static/
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES:
    - src/project/templates/
    - src/applications/hello/templates/
    - src/applications/main/templates/
  MODE_DEBUG: false
  MODE_PROFILING: false
  HOST: ""
  PORT: -1
  PROJECT_NAME: ""
  SECRET_KEY: ""
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0


development:
  PORT: 8000
  HOST: "localhost"
  SECRET_KEY: "1"


ci:
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2


heroku:
  MODE_DEBUG: false
  HOST: "mikepolo.herokuapp.com"
  SECRET_KEY: "1"
  VENV_SYNTHETIC: true
